spring:
  application:
    name: "order"
  datasource:
    driver-class-name: "oracle.jdbc.OracleDriver"
    username: "root"
    url: "jdbc:oracle:thin:@localhost:1521:xe"
    password: "root"
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: create
    show-sql: "true"
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: "true"

# server
server:
  port: 8080
